import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './providers'
import localFont from 'next/font/local'

const sentient = localFont({
  src: [
    {
      path: '../../public/fonts/Sentient-Variable.ttf'
    },
    {
      path: '../../public/fonts/Sentient-VariableItalic.ttf',
      style: 'italic'
    },
  ]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <head />
      <body className={sentient.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
